<?php
$translate = $this->plugin('translate');
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Source+Code+Pro|Lato:400,400italic,700,700italic');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
$this->headLink()->appendStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->appendStylesheet($this->assetUrl('css/style.css', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/global.js', 'Omeka'));
$this->trigger('view.layout');
$userBar = $this->userBar();
?>

<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html')->setAttribute('lang', $this->lang()); ?>
<?php echo $this->headMeta(); ?>  
<?php echo $this->headTitle(); ?>
<?php echo $this->headLink(); ?>
<?php echo $this->headStyle(); ?>
<?php echo $this->headScript(); ?>
<link href="/rivetlandingpagescripts/styles.css" rel="stylesheet"/>
<link rel="stylesheet" href="https://unpkg.com/rivet-core@2.1.0/css/rivet.min.css">
<link href="/rivetlandingpagescripts/microsite.css" rel="stylesheet"/>

<a class="rvt-header-wrapper__skip-link" href="#content" aria-label="Skip to main content">Skip to main content</a>
  <div class="rvt-header-global">
    <div class="rvt-container-xl">
      <div class="rvt-header-global__inner">
        <div class="rvt-header-global__logo-slot">
          <a class="rvt-lockup" href="https://www.iu.edu">  
            <!-- Trident logo -->
            <div class="rvt-lockup__tab">
              <svg xmlns="http://www.w3.org/2000/svg" class="rvt-lockup__trident" viewBox="0 0 28 34">
                <path d="M-3.34344e-05 4.70897H8.83308V7.174H7.1897V21.1426H10.6134V2.72321H8.83308V0.121224H18.214V2.65476H16.2283V21.1426H19.7889V7.174H18.214V4.64047H27.0471V7.174H25.0614V23.6761L21.7746 26.8944H16.2967V30.455H18.214V33.8787H8.76463V30.592H10.6819V26.8259H5.20403L1.91726 23.6077V7.174H-3.34344e-05V4.70897Z" fill="currentColor"></path>
              </svg>
            </div>
            <!-- Website or application title -->
            <div class="rvt-lockup__body">
              <span class="rvt-lockup__title">Indiana University</span>
            </div>
          </a>
        </div>
      </div>
    </div>
  </div>
</head>




 <?php echo $this->htmlElement('body')->appendAttribute('class', 'minimal'); ?>

 <div id="content" role="main">
     <?php echo $this->messages(); ?>
     <?php echo $this->content; ?>
 </div>
       
<footer id="footer" role="contentinfo" itemscope="itemscope" itemtype="http://schema.org/CollegeOrUniversity">
    <div class="row pad">
        <p class="signature">
            <a href="https://www.iu.edu/index.html" class="signature-link signature-img">
                <img src="//assets.iu.edu/brand/3.3.x/iu-sig-formal.svg" alt="Indiana University"/>
            </a>
        </p>
        <p class="copyright">
                <span class="line-break">
                    <a href="https://accessibility.iu.edu/assistance/index.html" id="accessibility-link" title="Having trouble accessing this web page content? Please visit this page for assistance.">Accessibility</a>
                     | 
                    <a href="https://uits.iu.edu/privacy/" id="privacy-policy-link">Privacy Notice</a>
                </span>
                <span class="hide-on-mobile"> | </span>
                <a href="https://www.iu.edu/copyright/index.html">Copyright</a>
                 &#169; 2024 
                <span class="line-break-small">
                    The Trustees of 
                    <a href="https://www.iu.edu/index.html" itemprop="url">
                        <span itemprop="name">Indiana University</span>
                    </a>
                </span>
        </p>
        </div>
    </footer>
    </body>
</html>
