<?php $escape = $this->plugin('escapeHtml'); ?>
<?php   

$user = $this->identity();
$useremail = $user->getEmail();


	
$sql = "select * from userjobs where email=\"".$useremail."\" AND dateCreated > now() - interval 1 day ORDER BY dateCreated DESC"; 
		$mysqli = mysqli_connect("[host_name]", "[database user]", "database user password", "database name");
		//$mysqli = $services->get('Omeka\Connection');
		$result = mysqli_query($mysqli, $sql);
	
       
		echo "<table class=\"table\">";
        echo "<tr class=\"header\">";
        echo "<td>Date</td>";
        echo "<td>Size (MB)</td>";
        echo "<td>Status</td>";
        echo "<td>Collection</td>";
        echo "<td>Download URL</td>";
        echo "</tr>";
                    
               while ($row = mysqli_fetch_row($result)) {
                   echo "<tr>";
                   echo "<td>".$row[3]."</td>";
                   echo "<td>".$row[4]."</td>";
                   echo "<td>".$row[5]."</td>";
                   echo "<td>".$row[6]."</td>";

                   
                   if ($row[5]=="completed") {                		
                   echo "<td><a href=\"".$row[7]."\">Click to download</a></td>";}
                   elseif ($row[5]=="failed") {                		
                   echo "<td>Please resubmit</td>";}
                   	else { 
                   	echo "<td>Pending</td>";
                   	}
                   	
                   echo "</tr>";
               }
               
                  echo "</table>";
    

?>
