apiVersion: v1
kind: Secret
metadata:
  name: omekas-secrets
  namespace: {{ include "omekas.namespace" . }}
  labels:
    {{- include "omekas.labels" . | nindent 4 }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.mysqlRootPassword | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.secrets.mysqlPassword | b64enc | quote }}
  OMEKA_ADMIN_PASSWORD: {{ .Values.secrets.omekaAdminPassword | b64enc | quote }}
  OIDC_CLIENT_SECRET: {{ .Values.secrets.oidcClientSecret | b64enc | quote }}
