
<?php
$translate = $this->plugin('translate');
$this->htmlElement('body')->appendAttribute('class', 'site browse front');
$title = $this->setting('installation_title', 'Omeka S');
$subtitle = $translate('Sites');
$this->headTitle($subtitle);
$this->trigger('view.layout');
$userBar = $this->userBar();

?>

<h1><?php echo $this->hyperlink($title, $this->url('top', ['action' => 'index'])); ?></h1>

<?php 
$user = $this->identity();
//$user = '';
if ($user != null) {
	 $useremail = $user->getEmail();
	 echo 'Welcome '.$useremail; }
else
	echo '<div>
            Please <a href="https://avl.sds.uits.iu.edu/oidc/login">Log in</a>
          </div>';
 ?>




<p>The IEEE SciVis Contest Share provides access to datasets used for the annual IEEE SciVis Contest. 
</p>

<?php if ($sites): ?>



<h2 class="site-list-heading"><?php //echo $subtitle; ?></h2>

<div class="site-list">
<?php
foreach ($sites as $site):
    echo $this->partial('common/site-list-entry', ['site' => $site, 'showSummary' => true, 'showThumbnail' => true]);
endforeach;
?>
</div>


<?php endif; ?>


<?php 
$user = $this->identity();
if ($user = null) {
    
$translate = $this->plugin('translate');
$this->htmlElement('body')->appendAttribute('class', 'site browse front');
$title = $this->setting('installation_title', 'Omeka S');
$subtitle = $translate('Sites');
$this->headTitle($subtitle);
$this->trigger('view.layout');
$userBar = $this->userBar();
?> 
<h1><?php echo $this->hyperlink($title, $this->url('top', ['action' => 'index'])); ?></h1>
<p>The IEEE SciVis Contest Share provides access to datasets used for the annual IEEE SciVis Contest. </p>

<?php if ($sites): ?>
<h2 class="site-list-heading"><?php //echo $subtitle; 
?></h2>

<div class="site-list">
<?php
foreach ($sites as $site):
    echo $this->partial('common/site-list-entry', ['site' => $site, 'showSummary' => true, 'showThumbnail' => true]);
	endforeach;
?>
</div>
<?php endif; }

else  
	echo '<meta content="text/html; charset=" http-equiv="content-type" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="Testing login page for Omeka S SDS instance.  ">
    <meta name="robots" content="max-snippet:-1, max-image-preview:large, max-video-preview:-1">
    <link rel="canonical" href="https://uits.iu.edu/services/accounts-and-email/google" />
        <link rel="shortcut icon" href="https://assets.iu.edu/favicon.ico" type="image/x-icon">

    <!-- Open Graph Meta-->
    <meta property="og:title" content="IEEE SciVis Contest SDS">
    <meta property="og:description" content="Access IEEE SciVis Contest datasets through the Scholarly Data Share service.  ">
    <meta property="og:url" content="https://uits.iu.edu/services/">
 
    <link as="font" crossorigin="" href="https://fonts.iu.edu/fonts/benton-sans-regular.woff" rel="preload" type="font/woff2" />
    <link as="font" crossorigin="" href="https://fonts.iu.edu/fonts/benton-sans-bold.woff" rel="preload" type="font/woff2" />
    <link href="https://unpkg.com/rivet-core@2.0.0-alpha.3/css/rivet.min.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" rel="stylesheet" />
    <link href="https://coreapis.sitehost.iu.edu/feedback/static/css/rivet-footer-iu-edu.css" rel="stylesheet"/>

 <link href="/rivetlandingpagescripts/styles.css" rel="stylesheet"/>
 <link href="/rivetlandingpagescripts/microsite.css" rel="stylesheet"/>
    
    
<main id="main-content">
    <div class="inner">
    <div class="rvt-c-hero rvt-c-hero--subtle">
        <div class="rvt-container-lg">
            <div class="rvt-row rvt-row--loose">
                <div class="rvt-cols-8-md">
                  <span class="rvt-c-hero__eyebrow">Scholarly Data Share</span>
                    <h1 class="rvt-c-hero__title [ rvt-text-bold rvt-ts-36 rvt-lh-title ]">IEEE SciVis Contest Share</h1>
                    <div style="color=#000;" class="rvt-c-hero__teaser [ rvt-m-top-lg rvt-m-bottom-none rvt-ts-18 ]">
                        The IEEE SciViz Contest Share provides access to datasets generated for the annual IEEE SciVis Contest. </div>
                        <div class="rvt-m-top-lg rvt-m-top-xl-md-up">
                            <a href="https://avl.sds.uits.iu.edu/IEEE_SciVis_Contest/oidc/login" class="rvt-button rvt-button--link rvt-m-right-md" >Log in to IEEE SciViz Contest Share</a>
                        </div>
                        
                        <div class="snippet hero-bottom">
                                                <br>
                                                <p class="hero__guest-account">Need an IU Guest account? <a href="https://login.iu.edu/guest?serviceName="><strong>Create one now</strong></a></p>
                                            </div>                      
                </div>
            </div>
        </div>
    </div>
</div>

';



