<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource browse');

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();


$query = $this->params()->fromQuery();
$itemSetShow = isset($itemSet);
if ($itemSetShow):
    $this->htmlElement('body')->appendAttribute('class', 'item-set');
    $query['item_set_id'] = $itemSet->id();
endif;
if ($itemSetShow):
    $relationTerm = 'dcterms:relation';
    $downloadMetadata = $relationTerm ? $itemSet->value($relationTerm, ['lang' => ($filterLocale ? [$lang, ''] : null)]) : $item->displayDescription(null, ($filterLocale ? [$lang, ''] : null));
endif;


$sortHeadings = [
    [
        'label' => $translate('Title'),
        'value' => 'dcterms:title'
    ],
    [
        'label' => $translate('Identifier'),
        'value' => 'dcterms:identifier'
    ],
    [
        'label' => $translate('Class'),
        'value' => 'resource_class_label'
    ],
    [
        'label' => $translate('Created'),
        'value' => 'created'
    ],
];
?>

<?php if ($itemSetShow): ?>
    <?php echo $this->pageTitle($itemSet->displayTitle(null, ($filterLocale ? $lang : null)), 2); ?>
    <div class="metadata"><br/>
        <?php echo $itemSet->displayValues(); ?>
<?php 
  $user = $this->identity();
    if ($user != null) {
    $useremail = $user->getEmail();
             }  




if ($user == 'siscan') {
           echo "<p>Downloads are not currently available to your account. Please contact UITS GIS (uitsgis@iu.edu) for assistance.</p>";
                }

        elseif ($user != null) {

        echo "<a href=https://rds-sds-prd-1.uits.iu.edu:8080/isdp/pull?p=".$downloadMetadata."&uid=".$useremail." target=blank>Click here to download metadata</a>";

	}

if ($user == null):
                echo "<div style=\"margin-left:2%;\">";
                echo "Please <a href=\"https://gis.iu.edu/oidc/login\">login</a> to submit a download request.";
        endif;

?>
    
</div> <br>
    <div class="item-set-items">
    <?php echo '<h3>' . $escape($translate('Items')) . '</h3>'; ?>
<?php else: ?>
    <?php echo $this->pageTitle($translate('Items'), 2); ?>
<?php endif; ?>

<?php echo $this->searchFilters(); ?>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php echo $this->hyperlink($translate('Advanced search'), $this->url('site/resource', ['controller' => 'item', 'action' => 'search'], ['query' => $query], true), ['class' => 'advanced-search']); ?>
    <?php #echo $this->sortSelector($sortHeadings); ?>
</div>

<?php $this->trigger('view.browse.before'); ?>
<ul class="resource-list">
<?php
$headingTerm = $this->siteSetting('browse_heading_property_term');
//$bodyTerm = $this->siteSetting('browse_body_property_term');
$bodyTerm = 'dcterms:description';
foreach ($items as $item):
    $heading = $headingTerm ? $item->value($headingTerm, ['default' => $translate('[Untitled]'), 'lang' => ($filterLocale ? [$lang, ''] : null)]) : $item->displayTitle(null, ($filterLocale ? [$lang, ''] : null));
    $body = $bodyTerm ? $item->value($bodyTerm, ['lang' => ($filterLocale ? [$lang, ''] : null)]) : $item->displayDescription(null, ($filterLocale ? [$lang, ''] : null));
?>
    <li class="item resource">
        <?php if ($itemThumbnail = $this->thumbnail($item, 'medium')): ?>
        <?php echo $item->linkRaw($itemThumbnail); ?>
        <?php endif; ?>
        <h3><?php echo $item->link($heading); ?></h3>
        <?php if ($body): ?>
        <div class="description"><?php echo $escape($body); ?></div>
        <?php endif; ?>
    </li>
<?php endforeach; ?>
</ul>
<?php echo ($itemSetShow) ? '</div>' : ''; ?>
<?php $this->trigger('view.browse.after'); ?>
<?php echo $this->pagination(); ?>
