services:

  omekas:
    build: .
    depends_on:
      - omekas_db
    container_name: omekas
    ports:
      - "8000:80"
    restart: unless-stopped
    env_file: "development.env"
    volumes:
      - omekas:/var/www/html/volume:Z

  omekas_db:
    image: mysql:latest
    container_name: omekas_db
    restart: unless-stopped
    volumes:
      - omeka_db:/var/lib/mysql:Z
    env_file: "development.env"
  
volumes:
  omeka_db:
  omekas:
