services:
  omekas:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - omekas_db
    container_name: omekas
    ports:
      - "8000:80"
    restart: unless-stopped
    env_file: ".development.env"
    environment:
      OMEKA_MODULES: |
        Common
        PageBlocks
        CSVImport
        HideProperties
        Log
        CustomOntology
        Sitemaps
        Shortcode
        OIDC: https://github.com/webgisdeveloper/omeka-s-module-oidc
    # environment:
    #   OMEKA_MODULES: |
    #     Common: https://github.com/Daniel-KM/Omeka-S-module-Common
    #     BulkEdit: https://gitlab.com/Daniel-KM/Omeka-S-module-BulkEdit
    #     BulkExport: https://gitlab.com/Daniel-KM/Omeka-S-module-BulkExport
    #     CSVImport: https://github.com/Omeka-s-modules/CSVImport
    #     CustomOntology: https://gitlab.com/Daniel-KM/Omeka-S-module-CustomOntology
    #     FacetedBrowse: https://github.com/omeka-s-modules/FacetedBrowse
    #     FileSideload: https://github.com/omeka-s-modules/FileSideload
    #     HideProperties: https://github.com/zerocrates/HideProperties
    #     Log: https://gitlab.com/Daniel-KM/Omeka-S-module-Log
    #     NumericDataTypes: https://github.com/omeka-s-modules/NumericDataTypes
    #     RestrictedSites: https://github.com/ManOnDaMoon/omeka-s-module-RestrictedSites
    #     Shortcode: https://github.com/Daniel-KM/Omeka-S-module-Shortcode
    #     Sitemaps: https://github.com/ManOnDaMoon/omeka-s-module-Sitemaps
    #     Statistics: https://github.com/Daniel-KM/Omeka-s-module-Statistics
    #     ValueSuggest: https://github.com/omeka-s-modules/ValueSuggest
    #     OIDC: https://github.com/webgisdeveloper/omeka-s-module-oidc
    volumes:
      - omekas_volume:/var/www/html/volume:Z

  omekas_db:
    image: mysql:latest
    container_name: omekas_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - omeka_db:/var/lib/mysql:Z
    env_file: ".development.env"

volumes:
  omeka_db:
  omekas_volume:
