apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omekasmysql-pvc
  namespace: sdsfrontend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: omekasmysql
  namespace: sdsfrontend
spec:
  selector:
    matchLabels:
      app: omekasmysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: omekasmysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          envFrom:
            - configMapRef:
                name: omekas-env
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: omekasmysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: omekasmysql
  namespace: sdsfrontend
spec:
  ports:
    - port: 3306
  selector:
    app: omekasmysql
