
<?php
$translate = $this->plugin("translate");
$this->htmlElement("body")->appendAttribute("class", "login");
?>
    <meta content="text/html; charset=" http-equiv="content-type" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="Login page for IEEE SciVis Contest SDS instance.">
    <meta name="robots" content="max-snippet:-1, max-image-preview:large, max-video-preview:-1">
    <link rel="canonical" href="https://uits.iu.edu/services/accounts-and-email/google" />
    <link rel="shortcut icon" href="https://assets.iu.edu/favicon.ico" type="image/x-icon">

    <!-- Open Graph Meta-->
    <meta property="og:title" content="SciVis IEEE Contest SDS">
    <meta property="og:description" content="Access IEEE SciVis Contest datasets through the Scholarly Data Share service.">
    <meta property="og:url" content="https://uits.iu.edu/services/">

    <link as="font" crossorigin="" href="https://fonts.iu.edu/fonts/benton-sans-regular.woff" rel="preload" type="font/woff2" />
    <link as="font" crossorigin="" href="https://fonts.iu.edu/fonts/benton-sans-bold.woff" rel="preload" type="font/woff2" />
    <link href="https://unpkg.com/rivet-core@2.0.0-alpha.3/css/rivet.min.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" rel="stylesheet" />
    <link href="https://coreapis.sitehost.iu.edu/feedback/static/css/rivet-footer-iu-edu.css" rel="stylesheet"/>

    <link href="/rivetlandingpagescripts/styles.css" rel="stylesheet"/>
    <link href="/rivetlandingpagescripts/microsite.css" rel="stylesheet"/>


<main id="main-content">
    <div class="inner">
    <div class="rvt-c-hero rvt-c-hero--subtle">
        <div class="rvt-container-lg">
            <div class="rvt-row rvt-row--loose">
                <div class="rvt-cols-8-md">
                  <span class="rvt-c-hero__eyebrow">Scholarly Data Share</span>
                    <h1 class="rvt-c-hero__title [ rvt-text-bold rvt-ts-36 rvt-lh-title ]">IEEE SciVis Contest Share</h1>
                    <div style="color=#000;" class="rvt-c-hero__teaser [ rvt-m-top-lg rvt-m-bottom-none rvt-ts-18 ]">
                        The SciVis Contest is held each year as a part of the IEEE VIS Conference. This site preserves and shares the data, documentation, and submissions (where available) from past contests as a learning resource for students, scientists, and visualization professionals. </div>
                        <div class="rvt-m-top-lg rvt-m-top-xl-md-up">
                            <a href="http://localhost:8000/oidc/login" class="rvt-button rvt-button--link rvt-m-right-md" >Log in to IEEE SciViz Contest Share</a>
                        </div>

                        <div class="snippet hero-bottom">
                            <br>
                        	<p class="hero__guest-account">Need an IU Guest account? <a href="https://login.iu.edu/guest?serviceName=vwhl"><strong>Create one now</strong></a></p>
                        </div>
                </div>
                </div>
            </div>
        </div>
    </div>
</div>
