<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700italic,700');
$this->headScript()->prependFile($this->assetUrl('js/default.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->jsTranslate();
$banner = $this->themeSettingAssetUrl('banner');
$bannerHeight = $this->themeSetting('banner_height');
$bannerHeightMobile = $this->themeSetting('banner_height_mobile');
$bannerPosition = ($this->themeSetting('banner_position')) ? str_replace('_','-', $this->themeSetting('banner_position')) : 'center';
$this->trigger('view.layout');
$userBar = $this->userBar();

?>
<?php echo $this->doctype(); ?>
 <link href="/rivetlandingpagescripts/styles.css" rel="stylesheet"/>
 <link href="/rivetlandingpagescripts/microsite.css" rel="stylesheet"/>
<link rel="stylesheet" href="https://unpkg.com/rivet-core@2.1.0/css/rivet.min.css">

<header class="rvt-header-wrapper">
  <!-- Hidden link for keyboard users to skip to main content -->
<a class="rvt-header-wrapper__skip-link" href="#content" aria-label="Skip to main content">Skip to main content</a>
 
<div class="rvt-header-global">
    <div class="rvt-container-xl">
      <div class="rvt-header-global__inner">
        <div class="rvt-header-global__logo-slot">
          <a class="rvt-lockup" href="https://www.iu.edu/">  
            <!-- Trident logo -->
            <div class="rvt-lockup__tab">
              <svg xmlns="http://www.w3.org/2000/svg" class="rvt-lockup__trident" viewBox="0 0 28 34">
                <path d="M-3.34344e-05 4.70897H8.83308V7.174H7.1897V21.1426H10.6134V2.72321H8.83308V0.121224H18.214V2.65476H16.2283V21.1426H19.7889V7.174H18.214V4.64047H27.0471V7.174H25.0614V23.6761L21.7746 26.8944H16.2967V30.455H18.214V33.8787H8.76463V30.592H10.6819V26.8259H5.20403L1.91726 23.6077V7.174H-3.34344e-05V4.70897Z" fill="currentColor"></path>
              </svg>
            </div>
            <!-- Website or application title -->
            <div class="rvt-lockup__body">
              <span class="rvt-lockup__title">Indiana University</span>
            </div>
          </a>
        </div>
      </div>
    </div>
  </div>
</header>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
        
        <style>
            <?php if ($accentColor = $this->themeSetting('accent_color')): ?>
            a:link,
            a:visited {
                color: <?php echo $accentColor; ?>
            }
            
            a:active,
            a:hover {
                color: <?php echo $accentColor; ?>;
                opacity: .75;
            }
            <?php endif; ?>

            .banner {
                height: <?php echo ($bannerHeight !== '') ? $bannerHeight: 'auto'  ?>;
                align-items: <?php echo $bannerPosition; ?>;
            }
            <?php if ($bannerHeightMobile !== ''): ?>
                @media screen and (max-width:640px) {
                    .banner {
                        height: <?php echo $bannerHeightMobile; ?>;
                    }
                }
            <?php endif; ?>
        </style>
    </head>

    <?php echo $this->htmlElement('body'); ?>
    <!-- <a id="skipnav" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>-->
        <?php echo $userBar; ?>
        <header>
        <!--<h2 style="margin-left: -2%;" ><?php echo $this->hyperlink($this->setting('installation_title', 'Omeka S'), $this->url('top', ['action' => 'index'])); ?></h2>
		-->
            <h1 class="site-title">
                <a href="<?php echo $site->url(); ?>">
                <?php if ($this->themeSetting('logo')): ?>
                    <img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
                <?php else: ?>
                    <?php echo $escape($siteTitle); ?>
                <?php endif; ?>
                </a>
            </h1>
            <div id="search">
                <?php echo $this->partial('common/search-form'); ?>
            </div>

            <nav>
            <?php
            echo $site->publicNav()->menu()->renderMenu(null, [
                'maxDepth' => $this->themeSetting('nav_depth') - 1
            ]);
            ?>
            </nav>
        </header>
        <?php if ($banner): ?>
        <div class="banner">
            <img src="<?php echo $this->themeSettingAssetUrl('banner'); ?>" title="Banner">
        </div>
        <?php endif; ?>
        <div id="content" role="main">
            <?php echo $this->content; ?>
        </div>

<footer id="footer" role="contentinfo" itemscope="itemscope" itemtype="http://schema.org/CollegeOrUniversity">
        <div class="row pad">
            <p class="signature">
                <a href="https://www.iu.edu/index.html" class="signature-link signature-img">
                    <img src="//assets.iu.edu/brand/3.3.x/iu-sig-formal.svg" alt="Indiana University"/>
                </a>
            </p>

            <p class="copyright">
                <span class="line-break">
                    <a href="https://accessibility.iu.edu/assistance/index.html" id="accessibility-link" title="Having trouble accessing this web page content? Please visit this page for assistance.">Accessibility</a>
                     | 
                    <a href="https://uits.iu.edu/privacy" id="privacy-policy-link">Privacy Notice</a>
                </span>
                <span class="hide-on-mobile"> | </span>
                <a href="https://www.iu.edu/copyright/index.html">Copyright</a>
                 &#169; 2025 
                <span class="line-break-small">
                    The Trustees of 
                    <a href="https://www.iu.edu/index.html" itemprop="url">
                        <span itemprop="name">Indiana University</span>
                    </a>
                </span>
            </p>
        </div>
    </footer>
    </body>
</html>
